"""add merma table

Revision ID: 0f0698bd44ed
Revises: e9c110729fd3
Create Date: 2026-07-06 02:02:14.637965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f0698bd44ed'
down_revision: Union[str, None] = 'e9c110729fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mermas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion_productiva_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('pileta_id', sa.Integer(), nullable=True),
    sa.Column('causa_merma_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('litros > 0', name='ck_mermas_litros_positive'),
    sa.ForeignKeyConstraint(['causa_merma_id'], ['causas_merma.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['operacion_productiva_id'], ['operaciones_productivas.id'], ),
    sa.ForeignKeyConstraint(['pileta_id'], ['piletas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mermas_causa_merma_id', 'mermas', ['causa_merma_id'], unique=False)
    op.create_index('ix_mermas_fecha', 'mermas', ['fecha'], unique=False)
    op.create_index('ix_mermas_lote_id', 'mermas', ['lote_id'], unique=False)
    op.create_index('ix_mermas_operacion_productiva_id', 'mermas', ['operacion_productiva_id'], unique=False)
    op.create_index('ix_mermas_pileta_id', 'mermas', ['pileta_id'], unique=False)
    op.create_index('ix_mermas_responsable_id', 'mermas', ['responsable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mermas_responsable_id', table_name='mermas')
    op.drop_index('ix_mermas_pileta_id', table_name='mermas')
    op.drop_index('ix_mermas_operacion_productiva_id', table_name='mermas')
    op.drop_index('ix_mermas_lote_id', table_name='mermas')
    op.drop_index('ix_mermas_fecha', table_name='mermas')
    op.drop_index('ix_mermas_causa_merma_id', table_name='mermas')
    op.drop_table('mermas')
    # ### end Alembic commands ###
