"""add movimiento fisico table

Revision ID: 1ecc431c01f3
Revises: d24fb5bee252
Create Date: 2026-07-06 01:47:56.617750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1ecc431c01f3'
down_revision: Union[str, None] = 'd24fb5bee252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_fisicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion_productiva_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('pileta_origen_id', sa.Integer(), nullable=True),
    sa.Column('pileta_destino_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('litros > 0', name='ck_movimientos_fisicos_litros_positive'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['operacion_productiva_id'], ['operaciones_productivas.id'], ),
    sa.ForeignKeyConstraint(['pileta_destino_id'], ['piletas.id'], ),
    sa.ForeignKeyConstraint(['pileta_origen_id'], ['piletas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movimientos_fisicos_fecha', 'movimientos_fisicos', ['fecha'], unique=False)
    op.create_index('ix_movimientos_fisicos_lote_id', 'movimientos_fisicos', ['lote_id'], unique=False)
    op.create_index('ix_movimientos_fisicos_operacion_productiva_id', 'movimientos_fisicos', ['operacion_productiva_id'], unique=False)
    op.create_index('ix_movimientos_fisicos_pileta_destino_id', 'movimientos_fisicos', ['pileta_destino_id'], unique=False)
    op.create_index('ix_movimientos_fisicos_pileta_origen_id', 'movimientos_fisicos', ['pileta_origen_id'], unique=False)
    op.create_index('ix_movimientos_fisicos_responsable_id', 'movimientos_fisicos', ['responsable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movimientos_fisicos_responsable_id', table_name='movimientos_fisicos')
    op.drop_index('ix_movimientos_fisicos_pileta_origen_id', table_name='movimientos_fisicos')
    op.drop_index('ix_movimientos_fisicos_pileta_destino_id', table_name='movimientos_fisicos')
    op.drop_index('ix_movimientos_fisicos_operacion_productiva_id', table_name='movimientos_fisicos')
    op.drop_index('ix_movimientos_fisicos_lote_id', table_name='movimientos_fisicos')
    op.drop_index('ix_movimientos_fisicos_fecha', table_name='movimientos_fisicos')
    op.drop_table('movimientos_fisicos')
    # ### end Alembic commands ###
