"""add analisis enologico table

Revision ID: 6c6c4f1f5242
Revises: 996c39b5fbd1
Create Date: 2026-07-06 03:10:44.615396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c6c4f1f5242'
down_revision: Union[str, None] = '996c39b5fbd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis_enologicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('pileta_id', sa.Integer(), nullable=True),
    sa.Column('codigo_externo', sa.String(length=80), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('capacidad_litros', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tipo', sa.String(length=150), nullable=True),
    sa.Column('alcohol', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('azucar', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('volatil', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('acidez_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('anhidrido_libre', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('anhidrido_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('extracto_seco', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('absorbancia_420', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('absorbancia_520', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('absorbancia_620', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('intensidad', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('indice', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('suma_420_520_620', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('brix', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('oxigeno', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['pileta_id'], ['piletas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analisis_enologicos_bodega_id', 'analisis_enologicos', ['bodega_id'], unique=False)
    op.create_index('ix_analisis_enologicos_fecha', 'analisis_enologicos', ['fecha'], unique=False)
    op.create_index('ix_analisis_enologicos_lote_id', 'analisis_enologicos', ['lote_id'], unique=False)
    op.create_index('ix_analisis_enologicos_pileta_id', 'analisis_enologicos', ['pileta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analisis_enologicos_pileta_id', table_name='analisis_enologicos')
    op.drop_index('ix_analisis_enologicos_lote_id', table_name='analisis_enologicos')
    op.drop_index('ix_analisis_enologicos_fecha', table_name='analisis_enologicos')
    op.drop_index('ix_analisis_enologicos_bodega_id', table_name='analisis_enologicos')
    op.drop_table('analisis_enologicos')
    # ### end Alembic commands ###
