"""add fraccionamiento tables

Revision ID: 70812a3105dc
Revises: 0f0698bd44ed
Create Date: 2026-07-06 02:11:04.319386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70812a3105dc'
down_revision: Union[str, None] = '0f0698bd44ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraccionamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion_productiva_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operacion_productiva_id'], ['operaciones_productivas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fraccionamientos_fecha', 'fraccionamientos', ['fecha'], unique=False)
    op.create_index('ix_fraccionamientos_operacion_productiva_id', 'fraccionamientos', ['operacion_productiva_id'], unique=False)
    op.create_index('ix_fraccionamientos_responsable_id', 'fraccionamientos', ['responsable_id'], unique=False)
    op.create_table('fraccionamiento_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fraccionamiento_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('pileta_id', sa.Integer(), nullable=False),
    sa.Column('litros_consumidos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('litros_consumidos > 0', name='ck_fraccionamiento_detalles_litros_consumidos_positive'),
    sa.ForeignKeyConstraint(['fraccionamiento_id'], ['fraccionamientos.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['pileta_id'], ['piletas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fraccionamiento_detalles_fraccionamiento_id', 'fraccionamiento_detalles', ['fraccionamiento_id'], unique=False)
    op.create_index('ix_fraccionamiento_detalles_lote_id', 'fraccionamiento_detalles', ['lote_id'], unique=False)
    op.create_index('ix_fraccionamiento_detalles_pileta_id', 'fraccionamiento_detalles', ['pileta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fraccionamiento_detalles_pileta_id', table_name='fraccionamiento_detalles')
    op.drop_index('ix_fraccionamiento_detalles_lote_id', table_name='fraccionamiento_detalles')
    op.drop_index('ix_fraccionamiento_detalles_fraccionamiento_id', table_name='fraccionamiento_detalles')
    op.drop_table('fraccionamiento_detalles')
    op.drop_index('ix_fraccionamientos_responsable_id', table_name='fraccionamientos')
    op.drop_index('ix_fraccionamientos_operacion_productiva_id', table_name='fraccionamientos')
    op.drop_index('ix_fraccionamientos_fecha', table_name='fraccionamientos')
    op.drop_table('fraccionamientos')
    # ### end Alembic commands ###
