"""add password hash to usuario

Revision ID: 712aa262741b
Revises: b0f14f65fe17
Create Date: 2026-07-06 21:18:36.347257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '712aa262741b'
down_revision: Union[str, None] = 'b0f14f65fe17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###
