"""add producto terminado table

Revision ID: 76d9e7cac2d5
Revises: 70812a3105dc
Create Date: 2026-07-06 02:17:19.354371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '76d9e7cac2d5'
down_revision: Union[str, None] = '70812a3105dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_terminados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fraccionamiento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_producto_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('cantidad_unidades', sa.Integer(), nullable=False),
    sa.Column('volumen_unidad_ml', sa.Integer(), nullable=False),
    sa.Column('litros_totales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_produccion', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad_unidades > 0', name='ck_productos_terminados_cantidad_unidades_positive'),
    sa.CheckConstraint('litros_totales > 0', name='ck_productos_terminados_litros_totales_positive'),
    sa.CheckConstraint('volumen_unidad_ml > 0', name='ck_productos_terminados_volumen_unidad_ml_positive'),
    sa.ForeignKeyConstraint(['fraccionamiento_id'], ['fraccionamientos.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['tipo_producto_id'], ['tipos_producto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_productos_terminados_codigo')
    )
    op.create_index('ix_productos_terminados_fecha_produccion', 'productos_terminados', ['fecha_produccion'], unique=False)
    op.create_index('ix_productos_terminados_fraccionamiento_id', 'productos_terminados', ['fraccionamiento_id'], unique=False)
    op.create_index('ix_productos_terminados_lote_id', 'productos_terminados', ['lote_id'], unique=False)
    op.create_index('ix_productos_terminados_tipo_producto_id', 'productos_terminados', ['tipo_producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_productos_terminados_tipo_producto_id', table_name='productos_terminados')
    op.drop_index('ix_productos_terminados_lote_id', table_name='productos_terminados')
    op.drop_index('ix_productos_terminados_fraccionamiento_id', table_name='productos_terminados')
    op.drop_index('ix_productos_terminados_fecha_produccion', table_name='productos_terminados')
    op.drop_table('productos_terminados')
    # ### end Alembic commands ###
