"""add orden trabajo table

Revision ID: 814bb24d706c
Revises: 961aa2f84589
Create Date: 2026-07-06 12:18:41.732328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '814bb24d706c'
down_revision: Union[str, None] = '961aa2f84589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_orden_trabajo_id', sa.Integer(), nullable=True),
    sa.Column('pileta_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('operario_id', sa.Integer(), nullable=True),
    sa.Column('operacion_productiva_id', sa.Integer(), nullable=True),
    sa.Column('pileta_origen_id', sa.Integer(), nullable=True),
    sa.Column('pileta_destino_id', sa.Integer(), nullable=True),
    sa.Column('codigo_externo', sa.String(length=80), nullable=True),
    sa.Column('numero', sa.String(length=80), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('volumen_lleno', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('variedad', sa.String(length=150), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('insumo', sa.String(length=150), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('col1', sa.String(length=120), nullable=True),
    sa.Column('litros_a_trasegar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lleno_disponible', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('litros_por_cm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pasada_a_trazabilidad', sa.Boolean(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('fecha_completada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones_completada', sa.Text(), nullable=True),
    sa.Column('so2l_real', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['operacion_productiva_id'], ['operaciones_productivas.id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['pileta_destino_id'], ['piletas.id'], ),
    sa.ForeignKeyConstraint(['pileta_id'], ['piletas.id'], ),
    sa.ForeignKeyConstraint(['pileta_origen_id'], ['piletas.id'], ),
    sa.ForeignKeyConstraint(['tarea_orden_trabajo_id'], ['tareas_orden_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ordenes_trabajo_codigo_externo', 'ordenes_trabajo', ['codigo_externo'], unique=False)
    op.create_index('ix_ordenes_trabajo_fecha', 'ordenes_trabajo', ['fecha'], unique=False)
    op.create_index('ix_ordenes_trabajo_lote_id', 'ordenes_trabajo', ['lote_id'], unique=False)
    op.create_index('ix_ordenes_trabajo_numero', 'ordenes_trabajo', ['numero'], unique=False)
    op.create_index('ix_ordenes_trabajo_operacion_productiva_id', 'ordenes_trabajo', ['operacion_productiva_id'], unique=False)
    op.create_index('ix_ordenes_trabajo_operario_id', 'ordenes_trabajo', ['operario_id'], unique=False)
    op.create_index('ix_ordenes_trabajo_pileta_destino_id', 'ordenes_trabajo', ['pileta_destino_id'], unique=False)
    op.create_index('ix_ordenes_trabajo_pileta_id', 'ordenes_trabajo', ['pileta_id'], unique=False)
    op.create_index('ix_ordenes_trabajo_pileta_origen_id', 'ordenes_trabajo', ['pileta_origen_id'], unique=False)
    op.create_index('ix_ordenes_trabajo_tarea_orden_trabajo_id', 'ordenes_trabajo', ['tarea_orden_trabajo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ordenes_trabajo_tarea_orden_trabajo_id', table_name='ordenes_trabajo')
    op.drop_index('ix_ordenes_trabajo_pileta_origen_id', table_name='ordenes_trabajo')
    op.drop_index('ix_ordenes_trabajo_pileta_id', table_name='ordenes_trabajo')
    op.drop_index('ix_ordenes_trabajo_pileta_destino_id', table_name='ordenes_trabajo')
    op.drop_index('ix_ordenes_trabajo_operario_id', table_name='ordenes_trabajo')
    op.drop_index('ix_ordenes_trabajo_operacion_productiva_id', table_name='ordenes_trabajo')
    op.drop_index('ix_ordenes_trabajo_numero', table_name='ordenes_trabajo')
    op.drop_index('ix_ordenes_trabajo_lote_id', table_name='ordenes_trabajo')
    op.drop_index('ix_ordenes_trabajo_fecha', table_name='ordenes_trabajo')
    op.drop_index('ix_ordenes_trabajo_codigo_externo', table_name='ordenes_trabajo')
    op.drop_table('ordenes_trabajo')
    # ### end Alembic commands ###
