"""add recepcion uva and lote tables

Revision ID: 9299abe2ed48
Revises: 7cbc78b79a43
Create Date: 2026-07-06 01:36:45.941881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9299abe2ed48'
down_revision: Union[str, None] = '7cbc78b79a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recepciones_uva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('origen_uva_id', sa.Integer(), nullable=False),
    sa.Column('variedad_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('numero_ciu', sa.String(length=80), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cosecha', sa.Integer(), nullable=False),
    sa.Column('kilos_recibidos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('kilos_recibidos > 0', name='ck_recepciones_uva_kilos_positive'),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['origen_uva_id'], ['origenes_uva.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['variedad_id'], ['variedades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bodega_id', 'numero_ciu', 'cosecha', name='uq_recepciones_uva_bodega_numero_ciu_cosecha')
    )
    op.create_index('ix_recepciones_uva_bodega_id', 'recepciones_uva', ['bodega_id'], unique=False)
    op.create_index('ix_recepciones_uva_fecha', 'recepciones_uva', ['fecha'], unique=False)
    op.create_index('ix_recepciones_uva_origen_uva_id', 'recepciones_uva', ['origen_uva_id'], unique=False)
    op.create_index('ix_recepciones_uva_responsable_id', 'recepciones_uva', ['responsable_id'], unique=False)
    op.create_index('ix_recepciones_uva_variedad_id', 'recepciones_uva', ['variedad_id'], unique=False)
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('tipo_producto_id', sa.Integer(), nullable=False),
    sa.Column('estado_lote_id', sa.Integer(), nullable=False),
    sa.Column('recepcion_uva_id', sa.Integer(), nullable=True),
    sa.Column('variedad_principal_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('cosecha', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['estado_lote_id'], ['estados_lote.id'], ),
    sa.ForeignKeyConstraint(['recepcion_uva_id'], ['recepciones_uva.id'], ),
    sa.ForeignKeyConstraint(['tipo_producto_id'], ['tipos_producto.id'], ),
    sa.ForeignKeyConstraint(['variedad_principal_id'], ['variedades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bodega_id', 'codigo', name='uq_lotes_bodega_codigo')
    )
    op.create_index('ix_lotes_bodega_id', 'lotes', ['bodega_id'], unique=False)
    op.create_index('ix_lotes_estado_lote_id', 'lotes', ['estado_lote_id'], unique=False)
    op.create_index('ix_lotes_fecha_nacimiento', 'lotes', ['fecha_nacimiento'], unique=False)
    op.create_index('ix_lotes_recepcion_uva_id', 'lotes', ['recepcion_uva_id'], unique=False)
    op.create_index('ix_lotes_tipo_producto_id', 'lotes', ['tipo_producto_id'], unique=False)
    op.create_index('ix_lotes_variedad_principal_id', 'lotes', ['variedad_principal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lotes_variedad_principal_id', table_name='lotes')
    op.drop_index('ix_lotes_tipo_producto_id', table_name='lotes')
    op.drop_index('ix_lotes_recepcion_uva_id', table_name='lotes')
    op.drop_index('ix_lotes_fecha_nacimiento', table_name='lotes')
    op.drop_index('ix_lotes_estado_lote_id', table_name='lotes')
    op.drop_index('ix_lotes_bodega_id', table_name='lotes')
    op.drop_table('lotes')
    op.drop_index('ix_recepciones_uva_variedad_id', table_name='recepciones_uva')
    op.drop_index('ix_recepciones_uva_responsable_id', table_name='recepciones_uva')
    op.drop_index('ix_recepciones_uva_origen_uva_id', table_name='recepciones_uva')
    op.drop_index('ix_recepciones_uva_fecha', table_name='recepciones_uva')
    op.drop_index('ix_recepciones_uva_bodega_id', table_name='recepciones_uva')
    op.drop_table('recepciones_uva')
    # ### end Alembic commands ###
