"""add tarea orden trabajo table

Revision ID: 961aa2f84589
Revises: 1d5a4b938f85
Create Date: 2026-07-06 11:13:29.877407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '961aa2f84589'
down_revision: Union[str, None] = '1d5a4b938f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas_orden_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_tareas_orden_trabajo_nombre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas_orden_trabajo')
    # ### end Alembic commands ###
