"""add excel base model adjustments

Revision ID: 996c39b5fbd1
Revises: 9da86c79b725
Create Date: 2026-07-06 03:04:20.068727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '996c39b5fbd1'
down_revision: Union[str, None] = '9da86c79b725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificaciones_vino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_calificaciones_vino_nombre')
    )
    op.add_column('lotes', sa.Column('calificacion_vino_id', sa.Integer(), nullable=True))
    op.add_column('lotes', sa.Column('color', sa.String(length=50), nullable=True))
    op.create_index('ix_lotes_calificacion_vino_id', 'lotes', ['calificacion_vino_id'], unique=False)
    op.create_foreign_key('fk_lotes_calificacion_vino_id_calificaciones_vino', 'lotes', 'calificaciones_vino', ['calificacion_vino_id'], ['id'])
    op.add_column('movimientos_fisicos', sa.Column('codigo_externo', sa.String(length=80), nullable=True))
    op.create_index('ix_movimientos_fisicos_codigo_externo', 'movimientos_fisicos', ['codigo_externo'], unique=False)
    op.add_column('operaciones_productivas', sa.Column('codigo_externo', sa.String(length=80), nullable=True))
    op.create_index('ix_operaciones_productivas_codigo_externo', 'operaciones_productivas', ['codigo_externo'], unique=False)
    op.add_column('piletas', sa.Column('litros_por_cm', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_check_constraint('ck_piletas_litros_por_cm_positive', 'piletas', 'litros_por_cm > 0')
    op.add_column('recepciones_uva', sa.Column('semana', sa.Integer(), nullable=True))
    op.add_column('recepciones_uva', sa.Column('rto', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('recepciones_uva', sa.Column('finca', sa.String(length=150), nullable=True))
    op.add_column('recepciones_uva', sa.Column('inv', sa.String(length=80), nullable=True))
    op.add_column('recepciones_uva', sa.Column('cambio', sa.String(length=80), nullable=True))
    op.add_column('recepciones_uva', sa.Column('cuartel', sa.String(length=80), nullable=True))
    op.add_column('recepciones_uva', sa.Column('tachos', sa.Integer(), nullable=True))
    op.add_column('recepciones_uva', sa.Column('chofer', sa.String(length=120), nullable=True))
    op.add_column('recepciones_uva', sa.Column('cuit_cuil', sa.String(length=50), nullable=True))
    op.add_column('recepciones_uva', sa.Column('camion', sa.String(length=120), nullable=True))
    op.add_column('recepciones_uva', sa.Column('modelo', sa.String(length=120), nullable=True))
    op.add_column('recepciones_uva', sa.Column('patente', sa.String(length=50), nullable=True))
    op.add_column('recepciones_uva', sa.Column('bruto_kg', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('recepciones_uva', sa.Column('tara_kg', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('recepciones_uva', sa.Column('neto_kg', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('recepciones_uva', sa.Column('uva_real_kg', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('recepciones_uva', sa.Column('destino_vino', sa.String(length=120), nullable=True))
    op.add_column('recepciones_uva', sa.Column('brix_real', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('recepciones_uva', sa.Column('tenor_azucar', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('recepciones_uva', sa.Column('vasija', sa.String(length=80), nullable=True))
    op.create_index('ix_recepciones_uva_finca', 'recepciones_uva', ['finca'], unique=False)
    op.create_index('ix_recepciones_uva_inv', 'recepciones_uva', ['inv'], unique=False)
    op.create_index('ix_recepciones_uva_patente', 'recepciones_uva', ['patente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recepciones_uva_patente', table_name='recepciones_uva')
    op.drop_index('ix_recepciones_uva_inv', table_name='recepciones_uva')
    op.drop_index('ix_recepciones_uva_finca', table_name='recepciones_uva')
    op.drop_column('recepciones_uva', 'vasija')
    op.drop_column('recepciones_uva', 'tenor_azucar')
    op.drop_column('recepciones_uva', 'brix_real')
    op.drop_column('recepciones_uva', 'destino_vino')
    op.drop_column('recepciones_uva', 'uva_real_kg')
    op.drop_column('recepciones_uva', 'neto_kg')
    op.drop_column('recepciones_uva', 'tara_kg')
    op.drop_column('recepciones_uva', 'bruto_kg')
    op.drop_column('recepciones_uva', 'patente')
    op.drop_column('recepciones_uva', 'modelo')
    op.drop_column('recepciones_uva', 'camion')
    op.drop_column('recepciones_uva', 'cuit_cuil')
    op.drop_column('recepciones_uva', 'chofer')
    op.drop_column('recepciones_uva', 'tachos')
    op.drop_column('recepciones_uva', 'cuartel')
    op.drop_column('recepciones_uva', 'cambio')
    op.drop_column('recepciones_uva', 'inv')
    op.drop_column('recepciones_uva', 'finca')
    op.drop_column('recepciones_uva', 'rto')
    op.drop_column('recepciones_uva', 'semana')
    op.drop_constraint('ck_piletas_litros_por_cm_positive', 'piletas', type_='check')
    op.drop_column('piletas', 'litros_por_cm')
    op.drop_index('ix_operaciones_productivas_codigo_externo', table_name='operaciones_productivas')
    op.drop_column('operaciones_productivas', 'codigo_externo')
    op.drop_index('ix_movimientos_fisicos_codigo_externo', table_name='movimientos_fisicos')
    op.drop_column('movimientos_fisicos', 'codigo_externo')
    op.drop_constraint('fk_lotes_calificacion_vino_id_calificaciones_vino', 'lotes', type_='foreignkey')
    op.drop_index('ix_lotes_calificacion_vino_id', table_name='lotes')
    op.drop_column('lotes', 'color')
    op.drop_column('lotes', 'calificacion_vino_id')
    op.drop_table('calificaciones_vino')
    # ### end Alembic commands ###
