"""add venta granel tables

Revision ID: 9da86c79b725
Revises: 76d9e7cac2d5
Create Date: 2026-07-06 02:37:51.254907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9da86c79b725'
down_revision: Union[str, None] = '76d9e7cac2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas_granel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion_productiva_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('documento', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['operacion_productiva_id'], ['operaciones_productivas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ventas_granel_cliente_id', 'ventas_granel', ['cliente_id'], unique=False)
    op.create_index('ix_ventas_granel_fecha', 'ventas_granel', ['fecha'], unique=False)
    op.create_index('ix_ventas_granel_operacion_productiva_id', 'ventas_granel', ['operacion_productiva_id'], unique=False)
    op.create_index('ix_ventas_granel_responsable_id', 'ventas_granel', ['responsable_id'], unique=False)
    op.create_table('venta_granel_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_granel_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('pileta_id', sa.Integer(), nullable=False),
    sa.Column('litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('litros > 0', name='ck_venta_granel_detalles_litros_positive'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['pileta_id'], ['piletas.id'], ),
    sa.ForeignKeyConstraint(['venta_granel_id'], ['ventas_granel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_venta_granel_detalles_lote_id', 'venta_granel_detalles', ['lote_id'], unique=False)
    op.create_index('ix_venta_granel_detalles_pileta_id', 'venta_granel_detalles', ['pileta_id'], unique=False)
    op.create_index('ix_venta_granel_detalles_venta_granel_id', 'venta_granel_detalles', ['venta_granel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_venta_granel_detalles_venta_granel_id', table_name='venta_granel_detalles')
    op.drop_index('ix_venta_granel_detalles_pileta_id', table_name='venta_granel_detalles')
    op.drop_index('ix_venta_granel_detalles_lote_id', table_name='venta_granel_detalles')
    op.drop_table('venta_granel_detalles')
    op.drop_index('ix_ventas_granel_responsable_id', table_name='ventas_granel')
    op.drop_index('ix_ventas_granel_operacion_productiva_id', table_name='ventas_granel')
    op.drop_index('ix_ventas_granel_fecha', table_name='ventas_granel')
    op.drop_index('ix_ventas_granel_cliente_id', table_name='ventas_granel')
    op.drop_table('ventas_granel')
    # ### end Alembic commands ###
