"""add corte teorico tables

Revision ID: b0f14f65fe17
Revises: 814bb24d706c
Create Date: 2026-07-06 12:27:20.948186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0f14f65fe17'
down_revision: Union[str, None] = '814bb24d706c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cortes_teoricos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('operacion_productiva_id', sa.Integer(), nullable=True),
    sa.Column('codigo_externo', sa.String(length=80), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operacion_productiva_id'], ['operaciones_productivas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cortes_teoricos_codigo_externo', 'cortes_teoricos', ['codigo_externo'], unique=False)
    op.create_index('ix_cortes_teoricos_fecha', 'cortes_teoricos', ['fecha'], unique=False)
    op.create_index('ix_cortes_teoricos_operacion_productiva_id', 'cortes_teoricos', ['operacion_productiva_id'], unique=False)
    op.create_index('ix_cortes_teoricos_responsable_id', 'cortes_teoricos', ['responsable_id'], unique=False)
    op.create_table('corte_teorico_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corte_teorico_id', sa.Integer(), nullable=False),
    sa.Column('pileta_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('codigo_externo', sa.String(length=80), nullable=True),
    sa.Column('volumen_al_corte', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('varietal_snapshot', sa.String(length=150), nullable=True),
    sa.Column('volumen_actual_snapshot', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('alcohol', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('acidez_volatil', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('acidez_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('so2_libre', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('so2_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corte_teorico_id'], ['cortes_teoricos.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['pileta_id'], ['piletas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corte_teorico_detalles_corte_teorico_id', 'corte_teorico_detalles', ['corte_teorico_id'], unique=False)
    op.create_index('ix_corte_teorico_detalles_lote_id', 'corte_teorico_detalles', ['lote_id'], unique=False)
    op.create_index('ix_corte_teorico_detalles_pileta_id', 'corte_teorico_detalles', ['pileta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_corte_teorico_detalles_pileta_id', table_name='corte_teorico_detalles')
    op.drop_index('ix_corte_teorico_detalles_lote_id', table_name='corte_teorico_detalles')
    op.drop_index('ix_corte_teorico_detalles_corte_teorico_id', table_name='corte_teorico_detalles')
    op.drop_table('corte_teorico_detalles')
    op.drop_index('ix_cortes_teoricos_responsable_id', table_name='cortes_teoricos')
    op.drop_index('ix_cortes_teoricos_operacion_productiva_id', table_name='cortes_teoricos')
    op.drop_index('ix_cortes_teoricos_fecha', table_name='cortes_teoricos')
    op.drop_index('ix_cortes_teoricos_codigo_externo', table_name='cortes_teoricos')
    op.drop_table('cortes_teoricos')
    # ### end Alembic commands ###
