"""add operacion productiva table

Revision ID: d24fb5bee252
Revises: 9299abe2ed48
Create Date: 2026-07-06 01:42:26.727163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd24fb5bee252'
down_revision: Union[str, None] = '9299abe2ed48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operaciones_productivas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('anulada', sa.Boolean(), nullable=False),
    sa.Column('motivo_anulacion', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_operacion_id'], ['tipos_operacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operaciones_productivas_bodega_id', 'operaciones_productivas', ['bodega_id'], unique=False)
    op.create_index('ix_operaciones_productivas_fecha', 'operaciones_productivas', ['fecha'], unique=False)
    op.create_index('ix_operaciones_productivas_responsable_id', 'operaciones_productivas', ['responsable_id'], unique=False)
    op.create_index('ix_operaciones_productivas_tipo_operacion_id', 'operaciones_productivas', ['tipo_operacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operaciones_productivas_tipo_operacion_id', table_name='operaciones_productivas')
    op.drop_index('ix_operaciones_productivas_responsable_id', table_name='operaciones_productivas')
    op.drop_index('ix_operaciones_productivas_fecha', table_name='operaciones_productivas')
    op.drop_index('ix_operaciones_productivas_bodega_id', table_name='operaciones_productivas')
    op.drop_table('operaciones_productivas')
    # ### end Alembic commands ###
