"""add relacion genealogica lote table

Revision ID: e9c110729fd3
Revises: 1ecc431c01f3
Create Date: 2026-07-06 01:52:10.111795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9c110729fd3'
down_revision: Union[str, None] = '1ecc431c01f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relaciones_genealogicas_lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion_productiva_id', sa.Integer(), nullable=False),
    sa.Column('lote_padre_id', sa.Integer(), nullable=False),
    sa.Column('lote_hijo_id', sa.Integer(), nullable=False),
    sa.Column('litros_aportados', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_relacion', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('litros_aportados > 0', name='ck_relaciones_genealogicas_lote_litros_positive'),
    sa.CheckConstraint('lote_padre_id <> lote_hijo_id', name='ck_relaciones_genealogicas_lote_padre_hijo_distintos'),
    sa.ForeignKeyConstraint(['lote_hijo_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['lote_padre_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['operacion_productiva_id'], ['operaciones_productivas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operacion_productiva_id', 'lote_padre_id', 'lote_hijo_id', name='uq_relaciones_genealogicas_lote_operacion_padre_hijo')
    )
    op.create_index('ix_relaciones_genealogicas_lote_lote_hijo_id', 'relaciones_genealogicas_lote', ['lote_hijo_id'], unique=False)
    op.create_index('ix_relaciones_genealogicas_lote_lote_padre_id', 'relaciones_genealogicas_lote', ['lote_padre_id'], unique=False)
    op.create_index('ix_relaciones_genealogicas_lote_operacion_productiva_id', 'relaciones_genealogicas_lote', ['operacion_productiva_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relaciones_genealogicas_lote_operacion_productiva_id', table_name='relaciones_genealogicas_lote')
    op.drop_index('ix_relaciones_genealogicas_lote_lote_padre_id', table_name='relaciones_genealogicas_lote')
    op.drop_index('ix_relaciones_genealogicas_lote_lote_hijo_id', table_name='relaciones_genealogicas_lote')
    op.drop_table('relaciones_genealogicas_lote')
    # ### end Alembic commands ###
